sudo: required
services:
    - docker

before_install:
    - docker build -t manjesh/complex-client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true manjesh/complex-client-test npm test

after_success:
    - docker build -t manjesh/complex-client ./client
    - docker build -t manjesh/complex-nginx ./nginx
    - docker build -t manjesh/complex-server ./server
    - docker build -t manjesh/complex-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push to docker hub
    - docker push manjesh/complex-client
    - docker push manjesh/complex-nginx
    - docker push manjesh/complex-server
    - docker push manjesh/complex-worker