sudo: required
services:
    - docker

before_install:
    - docker build -t reachmanjesh/complex-client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true reachmanjesh/complex-client-test npm test

after_success:
    - docker build -t reachmanjesh/complex-client ./client
    - docker build -t reachmanjesh/complex-nginx ./nginx
    - docker build -t reachmanjesh/complex-server ./server
    - docker build -t reachmanjesh/complex-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push to docker hub
    - docker push reachmanjesh/complex-client
    - docker push reachmanjesh/complex-nginx
    - docker push reachmanjesh/complex-server
    - docker push reachmanjesh/complex-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: complex-docker
    env: ComplexDocker-env
    bucket_name: elasticbeanstalk-us-east-1-751514257437
    bucket_path: complex-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY